### ISSUE TITLE
support uv_prepare_t handle API on iotjs

### ISSUE THREAD

**Issue by sumin-lim** [Samsung/iotjs#1003]
I have some problem for using uv_prepare_t and uv_check_t handles on IoT.js.
While linking on the build, it returns "undefined referece to `uv_prepare_init` or `uv_check_init`.

These are sub-class of uv_handle_t and I've test on libuv like below.

https://github.com/libuv/libuv/blob/v1.x/docs/code/uvstop/main.c
gcc -Wall -o uv_stop main.c $(pkg-config --cflags --libs libuv)

It seems that there is no difference between libtuv and libuv. I guess it's the kind of linking problem(?or not) but I couldn't fix on IoT.js.
However, there's no problem on using uv_timer_t.

Can we use these handle(uv_prepare_t, uv_check_t) on IoT.js?

**Comment by glistening** [comment]
@sumin-lim Currently libtuv does not support `uv_prepare_init` or `uv_check_init`. We removed unnecessary functions in libtuv to reduce binary footprint. Till now, there have been no use cases for those.

To define `uv_prepare_init` and `uv_check_init`,

First, restore following lines in next to [this line](https://github.com/Samsung/libtuv/blob/master/src/unix/loop-watcher.c#L81)

```
UV_LOOP_WATCHER_DEFINE(prepare, PREPARE)
UV_LOOP_WATCHER_DEFINE(check, CHECK)
```

Then, the compiler will complain some functions are missing. We need to provide the related code that are  in uv, but not in libtuv.

I think the changes above should be enclosed with TIZEN guard so that other platform (especially for low-end OS) should not be affected.

**Comment by sumin-lim** [comment]
Thank you for answering. I'll use 'guard', only for Tizen code.
