### ISSUE TITLE
misc test takes too much time

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/iotjs#1045]
tools/precommit.py --test=misc took ~30 minutes on Travis, 2x more then the next-longest test.
I'd like to break the misc test into separate ones, so Travis tests complete quicker.
Indented are the three separate builds that I think do not belong there.

tools/precommit.py:237-251
    elif test == "misc":

        args = []
        if os.getenv('TRAVIS') != None:
            args = ['--travis']
        ex.check_run_cmd('tools/check_signed_off.sh', args)

        if not check_tidy(path.PROJECT_ROOT):
            ex.fail("Failed tidy check")

>>        build("debug", build_args)
>>        build("debug", ['--no-snapshot', '--jerry-lto']
                       + os_dependency_module['linux'] + build_args)

>>        build("debug", ['--iotjs-minimal-profile'] + build_args)

**Comment by daeyeon** [comment]
Apparently we can skip `--iotjs-minimal-profile` at least.

**Comment by glistening** [comment]
@tadziopazur Oh, I've found this issue after I pushed #1076. The solution is same as it is straightforward, and I also made `coverity` job skip unit-tests. After that patch, the longest job is reduced from 18m to 11m52s. The total job time is reduced from 1h10m to 52m.

@daeyeon I did not removed `--iotjs-minimal-profile` yet since it does not take long time, and I don't know why `--iotjs-minimal-profile` is added.

Could you any of you @tadziopazur or @daeyeon remove `--iotjs-minimal-profile` if it is safe to remove?
