### ISSUE TITLE
IoT.js port to Artik 10 Tizen compilation fails during GBS setup due to missing terminfo-base-xxx

### ISSUE THREAD

**Issue by pmarcinkiew** [Samsung/iotjs#1051]
The GBS compilation fails for Artik 10 version of IoT.js

```
=== the following packages failed to build due to missing build dependencies (1) ===
iotjs:
  have choice for terminfo-base needed by libncurses: terminfo-base-full terminfo-base-mini
  have choice for terminfo-base needed by libncurses6: terminfo-base-full terminfo-base-mini
```

I used ~/.gbs.conf:

```
root@bpower:/home/piotr/src# cat ~/.gbs.conf
[general]
profile = profile.tizen_unified

[profile.tizen_unified]
obs = obs.spin
repos = repo.public_4.0_base_arm, repo.tizen_unified

[profile.tizen_artik10]
obs = obs.spin
repos = repo.public_3.0_base_arm, repo.public_3_arm

[obs.spin]
url = http://168.219.209.58:81

[obs.tizen]
url = https://api.tizen.org
user = obs_viewer
passwdx = QlpoOTFBWSZTWRP5nYMAAB6fgCAAeUA9mr+QBvzF4CAAVGAZDTRoDI0YBlCKeptQBoA0aGZIAottAkltEPOK7BAFXE9mTUzocPMzQRkPoPpNwEZx3rRQhxkXmGHS6wCjHskyVCP4u5IpwoSAn8zsGA==

[repo.public_3_arm] 
url = http://download.tizen.org/releases/milestone/tizen/3.0.m2/common_artik/tizen-common-artik_20170111.3/repos/arm-wayland/packages/
user =
passwdx = 

[repo.tizen_unified]
url=http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/
user=
passwdx=

[repo.base_arm]
url=http://download.tizen.org/snapshots/tizen/base/latest/repos/arm/
user=
passwdx=


[repo.public_3.0_base_arm]
url = http://download.tizen.org/snapshots/tizen/base/latest/repos/arm/packages/armv7l/
user = 
passwdx = 

[repo.public_4.0_base_arm]
url = http://download.tizen.org/snapshots/tizen/base/latest/repos/arm/packages/
user = 
passwdx =

```

Please find below my full compilation log:

```
root@bpower:/home/piotr/src/iotjs_gbs# ./config/tizen/gbsbuild.sh 
******************************************************************
*                       Tizen GBS build                          *
*                                                                *
* Please input user, passwd of http://Tizen.org on '~/.gbs.conf' *
* For more information, please read Guide Docs. folder           *
* ~/.gbs.conf sample is at 'config/tizen/sample.gbs.conf'.       *
*                                                                *
******************************************************************
[Warning] This working folder will be copied to ../iotjs_tizen_gbs Are you sure to continue? (y/n) y
copy from /home/piotr/src/iotjs_gbs to ../iotjs_tizen_gbs

(1) Now, cloning submodules. 

(2) Update submodules... 

(3) Remove compiler specified lines on CMake

(4) 3 files have been modified.
Initialized empty Git repository in /home/piotr/src/iotjs_tizen_gbs/.git/
Switched to a new branch 'tizen_gbs'
[tizen_gbs (root-commit) 27f85e3] Initial commit
 3514 files changed, 324844 insertions(+)
 create mode 100644 .clang-format
 create mode 100644 .gbs.conf
[omitted]
 create mode 100644 tools/module_analyzer.py
 create mode 100755 tools/precommit.py
 create mode 100644 tools/test_runner.js

(5) Calling core gbs build command
gbs build -A armv7l --include-all --clean
info: generate repositories ...
warning: No local package repository for arch armv7l
info: build conf has been downloaded at:
      /var/tmp/root-gbs/tizen_unified.conf
info: start building packages from: /home/piotr/src/iotjs_tizen_gbs (git)
2017-07-17 17:18 +0200
gbs 0.24.4
info: prepare sources...
info: start export source from: /home/piotr/src/iotjs_tizen_gbs ...
info: Creating (native) source archive iotjs-1.0.0.tar.gz from 'b1a5dc4a6a7fda18de7046099538f04913626029'
info: package files have been exported to:
     /root/GBS-ROOT/local/sources/tizen_unified/iotjs-1.0.0-0
info: retrieving repo metadata...
info: parsing package data...
info: building repo metadata ...
info: resolving skipped packages ...
info: package dependency resolving ...
info: *** Build Status Summary ***
=== the following packages failed to build due to missing build dependencies (1) ===
iotjs:
  have choice for terminfo-base needed by libncurses: terminfo-base-mini terminfo-base-full
  have choice for terminfo-base needed by libncurses6: terminfo-base-mini terminfo-base-full

=== Total succeeded built packages: (0) ===
info: generated html format report:
     /root/GBS-ROOT/local/repos/tizen_unified/armv7l/index.html
info: generated RPM packages can be found from local repo:
     /root/GBS-ROOT/local/repos/tizen_unified/armv7l/RPMS
info: generated source RPM packages can be found from local repo:
     /root/GBS-ROOT/local/repos/tizen_unified/armv7l/SRPMS
info: build logs can be found in:
     /root/GBS-ROOT/local/repos/tizen_unified/armv7l/logs
info: build roots located in:
     /root/GBS-ROOT/local/BUILD-ROOTS/scratch.armv7l.*
error: <gbs>some packages failed to be built
GBS Build failed!
root@bpower:/home/piotr/src/iotjs_gbs# 
```

**Comment by pmarcinkiew** [comment]
I have found solution for this issue:

https://github.com/Samsung/iotjs/pull/1058

**Comment by tadziopazur** [comment]
I had similar issue, with the gbs.conf as follows (removed presumably non-relevant lines).
Apparently the libstdc++ of required version is not present in Tizen OBS repositories.
How? Why?

> cat ~/.gbs.conf
[general]
profile = profile.tizen_unified

[profile.tizen_unified]
obs = obs.spin
repos = repo.public_4.0_base_arm, repo.tizen_unified

[obs.spin]
url = http://168.219.209.58:81

[repo.public_4.0_base_arm]
url = http://download.tizen.org/snapshots/tizen/base/latest/repos/arm/packages/
user = 
passwdx =

[repo.tizen_unified]
url=http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/
user=
passwdx=

The build log (removed git log spwe due to squashing of the repository structure):
> ./gbsbuild.sh 
******************************************************************
*                       Tizen GBS build                          *
*                                                                *
* Please input user, passwd of http://Tizen.org on '~/.gbs.conf' *
* For more information, please read Guide Docs. folder           *
* ~/.gbs.conf sample is at 'config/tizen/sample.gbs.conf'.       *
*                                                                *
******************************************************************
[Warning] This working folder will be copied to ../iotjs_tizen_gbs Are you sure to continue? (y/n) y
copy from /opt/iotjs/iotjs_lim.git to ../iotjs_tizen_gbs

(1) Now, cloning submodules. 

(2) Update submodules... 

(3) Remove compiler specified lines on CMake

(4) 3 files have been modified.
Initialized empty Git repository in /opt/iotjs/iotjs_tizen_gbs/.git/
Switched to a new branch 'tizen_gbs'
[tizen_gbs (root-commit) 0e57f22] Initial commit
 3530 files changed, 326744 insertions(+)
(...)
(5) Calling core gbs build command
gbs build -A armv7l --include-all --clean
info: generate repositories ...
warning: No local package repository for arch armv7l
info: build conf has been downloaded at:
      /var/tmp/t.wozniak-gbs/tizen_unified.conf
info: start building packages from: /opt/iotjs/iotjs_tizen_gbs (git)
2017-07-24 15:38 +0200
gbs 0.24.3
info: prepare sources...
info: start export source from: /opt/iotjs/iotjs_tizen_gbs ...
info: Creating (native) source archive iotjs-1.0.0.tar.gz from 'dfc16594e86221439d275477700a14bb835cea57'
info: package files have been exported to:
     /home/t.wozniak/GBS-ROOT/local/sources/tizen_unified/iotjs-1.0.0-0
info: retrieving repo metadata...
Use of uninitialized value $evr in concatenation (.) or string at /usr/lib/build/Build/Rpmmd.pm line 175.
info: parsing package data...
info: building repo metadata ...
info: resolving skipped packages ...
info: package dependency resolving ...
[sudo] password for t.wozniak: 
info: *** Build Status Summary ***
**## === the following packages failed to build due to missing build dependencies (1) ===
iotjs:
  nothing provides libstdc++.so.6(GLIBCXX_3.4.21) needed by libcynara-client
  nothing provides libstdc++.so.6(GLIBCXX_3.4.21) needed by libcynara-session**

=== Total succeeded built packages: (0) ===
info: generated html format report:
     /home/t.wozniak/GBS-ROOT/local/repos/tizen_unified/armv7l/index.html
info: generated RPM packages can be found from local repo:
     /home/t.wozniak/GBS-ROOT/local/repos/tizen_unified/armv7l/RPMS
info: generated source RPM packages can be found from local repo:
     /home/t.wozniak/GBS-ROOT/local/repos/tizen_unified/armv7l/SRPMS
info: build logs can be found in:
     /home/t.wozniak/GBS-ROOT/local/repos/tizen_unified/armv7l/logs
info: build roots located in:
     /home/t.wozniak/GBS-ROOT/local/BUILD-ROOTS/scratch.armv7l.*
error: <gbs>some packages failed to be built
GBS Build failed!

**Comment by pmarcinkiew** [comment]
I noticed that both my and @tadziopazur Ubuntu PC use GBS 0.24.3.

I upgraded my GBS to 0.24.6 version from tizen.org Ubuntu [package](http://download.tizen.org/tools/latest-release/Ubuntu_16.04/).

The build process is successful so it seems to be issue with backward compatibility of GBS but I'm not sure. I will close this issue and reopen it if errors with occur again.

**Comment by glistening** [comment]
I met error during gbs build. It seems similar to @pmarcinkiew's case. I am using gbs 0.23.2. I will update gbs to 0.24.6 or newer version, and remove GBS-ROOT, and try again.

```
(5) Calling core gbs build command
gbs build -A armv7l --include-all --clean
gbs:warning: plaintext password in config files will be replaced by encoded ones
info: generate repositories ...
info: build conf has been downloaded at:
      /var/tmp/brian-gbs/tizen_unified.conf
info: start building packages from: /home/brian/iotjs/iotjs_tizen_gbs (git)
2017-08-18 13:21 +0900
gbs 0.23.2
info: prepare sources...
info: start export source from: /home/brian/iotjs/iotjs_tizen_gbs ...
Argument "" isn't numeric in numeric eq (==) at /usr/bin/depanneur line 642.
warning: Deprecated option '--git-export-only', please use '--no-build' instead!
info: Creating (native) source archive iotjs-1.0.0.tar.gz from 'ba42c260f274ce58e562df5ae0e01539b08f6f90'
info: package files have been exported to:
     /home/brian/GBS-ROOT/local/sources/tizen_unified/iotjs-1.0.0-0
info: retrieving repo metadata...
info: parsing package data...
info: building repo metadata ...
info: resolving skipped packages ...
info: package dependency resolving ...
info: *** Build Status Summary ***
=== the following packages failed to build due to missing build dependencies (1) ===
iotjs:
  have choice for terminfo-base needed by libncurses: terminfo-base-mini terminfo-base-full
  have choice for terminfo-base needed by libncurses6: terminfo-base-mini terminfo-base-full

=== Total succeeded built packages: (0) ===
info: generated html format report:
     /home/brian/GBS-ROOT/local/repos/tizen_unified/armv7l/index.html
info: generated RPM packages can be found from local repo:
     /home/brian/GBS-ROOT/local/repos/tizen_unified/armv7l/RPMS
info: generated source RPM packages can be found from local repo:
     /home/brian/GBS-ROOT/local/repos/tizen_unified/armv7l/SRPMS
info: build logs can be found in:
     /home/brian/GBS-ROOT/local/repos/tizen_unified/armv7l/logs
info: build roots located in:
     /home/brian/GBS-ROOT/local/BUILD-ROOTS/scratch.armv7l.*
error: <gbs>some packages failed to be built
```
