### ISSUE TITLE
Assertion `fd > STDERR_FILENO' failed in uv__close

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#1246]
###### IoT.js version:

```
Checked revision: 9c1e57c
Build command: ./tools/build.py --buildtype=debug --target-arch=i686
```
###### OS:

```
Ubuntu 16.04.3 LTS
```
###### Test case:

```javascript
var fs = require('fs');
var http = require('http');

fs.closeSync(1)
http.request({host: "localhost", host: "127.0.0.1", method: "GET", path: "/", port: 10})
```

###### Backtrace:

```
uncaughtException: Error: socket hang up
iotjs: iotjs/deps/libtuv/src/unix/core.c:456: uv__close: Assertion `fd > STDERR_FILENO' failed.
bt
#0  0xf7fd8be9 in __kernel_vsyscall ()
#1  0xf7842ea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7844407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf783bd07 in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf783bd8b in __assert_fail () from /lib/i386-linux-gnu/libc.so.6
#5  0x08151913 in uv__close (fd=0) at iotjs/deps/libtuv/src/unix/core.c:456
#6  0x0815fab6 in uv__loop_close (loop=0x821f140 <default_loop_struct>) at iotjs/deps/libtuv/src/unix/loop.c:120
#7  0x0814d886 in uv_loop_close (loop=0x821f140 <default_loop_struct>) at iotjs/deps/libtuv/src/uv-common.c:479
#8  0x0805af01 in iotjs_entry (argc=3, argv=0xffffc374) at iotjs/src/iotjs.c:219
#9  0x08059ba6 in main (argc=3, argv=0xffffc374) at iotjs/iotjs_linux.c:19
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by glistening** [comment]
This assertion failure occurs because this test case close file descriptor 1 (STDOUT in linux) and http.request calls  `uv__stream_init`, which internally open a file descriptor (to reserve one file descriptor for handling EMFILE situation), meanwhile it returned file descriptor 1.

There are several choices:

1. Don't permit the users to close STDIN, STDOUT and STDERR.
2. Permit, but remove assert(`fd > STDERR_FILENO`) in `uv__close` since the file descriptor (0, 1, 2) may be used if closing them is permitted.
3. Don't fix at all. Keep the assert to give an alarm to user in debug mode. ("Hey, you closed standard file descriptor, do you really want it?")

I prefer option 3.

**Comment by glistening** [comment]
There is no opinion. Closing it without changing policy about closing STDIN, STDOUT and STDERR.
