### ISSUE TITLE
Regarding coding convention

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1262]
As we all know, coding convention helps to prevent errors and to manage code quality. While discussing a coding convention for IoT.js Code, the one for IoT.js was naturally mentioned in the discussion.

Please take a look at https://github.com/Samsung/iotjscode/issues/20 and share your opinion. The candidate list in the issue is also able to apply to IoT.js.

**Comment by glistening** [comment]
For strategy, I prefer `full` configurations. (i.e., apply all at once). Because whenever we modify the coding style rule, we have to run all tests on all reference board. I would like to minimize the step.

For eslint configuration, I prefer `eslint recommended`. ( airbnb configuration includes much ES6 rules which we currently don't/can't use, and I don't want to use airbnb ES5 config since it is deprecated. ) When we apply `eslint recommended` rules, some rules may not be applicable to our source base, then we could turn off problematic rules like google has done in google config. ( google config seems to be based on `eslint recommended`, and google customized config ).

**Comment by daeyeon** [comment]
https://github.com/Samsung/iotjs/pull/1270 is landed for this.
