### ISSUE TITLE
Possible to run on ESP8266?

### ISSUE THREAD

**Issue by maxogden** [Samsung/iotjs#136]
Hi, I am curious if it will ever be possible to run iotjs on the ESP8266 chip: https://github.com/esp8266/esp8266-wiki/wiki

The specs are quite limited:

- It's running at 80MHz
- 64KBytes of instruction RAM
- 96KBytes of data RAM
- 64KBytes boot ROM

But there is a firmware for it that implements Lua https://github.com/nodemcu/nodemcu-firmware

**Comment by seanshpark** [comment]
Hello, thank you for your interest on iotjs.  It seems that memory is not enough for iotjs.

Current version for STM32F4 version requires about 350KB image ROM and about 100K RAM(roughly). We have plans to reduce RAM size with JerryScript but for ROM, it may be hard.

**Comment by seanshpark** [comment]
https://github.com/nodemcu/nodemcu-firmware is very interesting.

**Comment by maxogden** [comment]
@seanshpark thanks for the reply! nodemcu is indeed quite cool, but I prefer node.js over lua :) 

So it seems that iotjs should be compatible with boards like this then?

- http://www.espruino.com/Pico 
- https://www.tindie.com/products/Fyberlabs/stm32-small-flex-module-401/

The appeal of the ESP8266 is the integrated wifi. It looks like the espruino shim http://www.espruino.com/ESP8266 is maybe the best way to get wifi connectivity from a device running iotjs

**Comment by maxogden** [comment]
@seanshpark also where does the name JerryScript come from? haha

**Comment by lemmaa** [comment]
@maxogden Hi, nice to meet you. Yes, we also think that IoT.js should compatible with such boards, eventually.

As of now, we just checked up the possibility of our approach, downsizing node.js for IoT with JerryScript, and just beginning long journey of development. But we don't know how small we can make it useful. 

The first thing we willing to do at this time is define the core modules or APIs for IoT.js under real world experience of IoT device development, and we  wanna do it with IoT community. Because it needs much consideration of many devices such as espruino pico and ESP8266, for example. 

I think you can help us. Join us! Thanks!

P.S. The name JerryScript is @egavrin's idea, inspired from the famous cartoon 'Tome and Jerry'. We also considering TomScript for test-suit of JerryScript or so. :)
For more information, the byte code used in JerryScript was originally named as 'High-fat cheese IR' and 'Low-fat cheese IR'.

**Comment by maxogden** [comment]
@lemmaa thanks for the information, very cool.

P.s. I wrote up a blog post about the project http://maxogden.com/iotjs-and-jerryscript.html
