### ISSUE TITLE
Duktape instead of JerryScript

### ISSUE THREAD

**Issue by drasko** [Samsung/iotjs#149]
Hi,
I would like to know your opinion on Duktape (http://duktape.org/) in comparison to JerryScript, and would it be complicated to replace IoT.js JS engines if needed?

BR,
Drasko

**Comment by mitizhi** [comment]
@drasko - I learned about both duktape and JerryScript just couple of minutes ago. That said, I just happened to see this presentation: http://www.slideshare.net/SamsungOSG/jerryscript-on-riot. (Actually that presentation is the reason I learned about JerryScript in the first place, and this question made me search for JerryScript.) On pages 13 and 14 there are comparison of memory and performance consumption of both JS implementations (running SunSpider 1.0.2 benchmarks). I am not able to comment on the test setup, but according to the figures JerryScript is clear winner in both low memory footprint and execution times.

**Comment by esevan** [comment]
@drasko IMHO, IoT.js is the IoT platform powered by JerryScript. Even though there's somewhat modularity (JerryScript Binding) between IoT.js API and JerryScript, which is able to be replaced by other JS engine such as Ducktape, I don't think it's easy to replace the JS engine since the difference of JerryScript API and DuckTape API. Moreover, as @mitizhi said, there's no certain reason to replace from Jerry to Duck according to [benchmark result](http://samsung.github.io/jerryscript/benchmark/benchmark.html)

**Comment by yichoi** [comment]
closing. no plan with Duktape right now.
