### ISSUE TITLE
How to run smoking test on target-board?

### ISSUE THREAD

**Issue by wuhanck** [Samsung/iotjs#1614]
I noticed that check_test.js had been removed.
So, how to run smoking test on target-board which is lack of python env?

**Comment by rtakacs** [comment]
The [js-remote-test](https://github.com/Samsung/js-remote-test) project helps to run the official IoT.js test-suite on the main target devices. It does not need to have Python interpreter on the board because the test-runner is based on communication (between a device and a host-PC). Please read the [README.md](https://github.com/Samsung/js-remote-test/blob/master/README.md) file for more information.  

Need to mention that js-remote-test is an automation tool for testing, so it builds iotjs and flashes the binary (with the test-suite) to the selected device. The test-runner is able to measure the binary size of iotjs and the run-time memory consumption (of the tests).

The js-remote-test project is used every day to test IoT.js on the supported devices. The results are published on the [iotjs-test-result](https://samsung.github.io/iotjs-test-results/) webpage.

I hope that I could help you :)

**Comment by wuhanck** [comment]
Thanks. It looks like a new piece of porting task for me. :(.
Anyway, thank you.
