### ISSUE TITLE
Print backtrace when aborting

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#201]
We had had feature of printing backtrace when aborting. removed while porting to Nuttx since there were no supporting from Nuttx to print out backtrace.
I think we can revive that feature at least for linux target.

**Comment by yichoi** [comment]
Closing issue. Please reopen it again if necessary.

- Issue description is not sufficient: It is unclear if 'backtrace' means JavaScript stack backtrace or native stack backtrace. (or something else?)
- Currently it's impossible to print JavaScript stack trace, since jerry doesn't support this feature.
- Since it is easy to get backtrace information in linux target using debugger support, printing native backtrace for linux target would not be so helpful.

**Comment by tobyZhou** [comment]
Hello, @yichoi . Thanks for your explanations!
I'm trying iotjs currently, just wonder for the second point, does it support printing JavaScript stack trace now? or it's still impossible to print JavaScript stack trace yet?

**Comment by tobyZhou** [comment]
hello. does anyone have idea about this? is it possible to print JavaScript stack trace.?

**Comment by TE-AmitSa** [comment]
I need back trace for "Native stack back trace", with symbol name. not merely with address only.
