### ISSUE TITLE
Making start up script for STM32F4

### ISSUE THREAD

**Issue by lemmaa** [Samsung/iotjs#239]

**Comment by seanshpark** [comment]
Can you explain more about this?

**Comment by lemmaa** [comment]
@seanshpark It means writing default boot script for NuttX, to make STM32F4 with IoT.js make do initialization and go to standby state after power on reset cycle.

**Comment by seanshpark** [comment]
OK, Thanks.
I think there can be two ways. First can be run iot.js by adding to nsh start-up script. This will be simple and can do right away. And the second, replace user entry point from nsh_main to iotjs_main. This can give more memory to iotjs since we can remove nsh and its library, I guess, but needs testing.
Either way, giving start-up script file name should be fixed, something like `/mnt/sdcard/startup.js`, so we can add application script to sdcard, plug-in and start.
One more question, can you please describe more about 'go to standby state' ?

**Comment by ILyoan** [comment]
@lemmaa @seanshpark Sorry, but it's still unclear for me What "start up script" means for.
So does it refer the first javascript will be run after boot?

**Comment by lemmaa** [comment]
@seanshpark Yes, the second one, replace `nsh` with IoT.js, is better. In my original intention, "start up script" means the NuttX boot script as in your first approach, because it's most simple way. Anyway, in general situation of production, removing `nsh` and get more memory is right choice I guess. 

In that case we may need another "start up script" for IoT.js itself as you mentioned. Actually it's not just start up script, it's "start up procedure" for IoT.js embedded devices, and your proposal looks good one.
'stanby state' means 'service ready' state after initialization process. From then on, users actually can access the service or use the functions which the device provides.

@ILyoan Is it still unclear for you? 'script' is not important. We need to define the 'procedure', script is just one example.

**Comment by yichoi** [comment]
It seems not essencial feature since we do not support STM32F4 as a main development target anymore.
