### ISSUE TITLE
cannot build on x86_64: ./tools/build.py

### ISSUE THREAD

**Issue by gridnow** [Samsung/iotjs#349]
==> Build libtuv

cmake /home/sihai.ysh/iotjs/deps/libtuv -DCMAKE_TOOLCHAIN_FILE=/home/sihai.ysh/iotjs/deps/libtuv/cmake/config/config_x86_64-linux.cmake -DCMAKE_BUILD_TYPE=debug -DTARGET_PLATFORM=x86_64-linux -DLIBTUV_CUSTOM_LIB_OUT=/home/sihai.ysh/iotjs/build/x86_64-linux/debug/deps/libtuv -DCMAKE_C_FLAGS=-D__LINUX__ -fno-builtin -D__x86_64__ -D__X86_64__ -g -DDEBUG -DENABLE_DEBUG_LOG -DCMAKE_CXX_FLAGS=-D__LINUX__ -fno-builtin -D__x86_64__ -D__X86_64__ -g -DDEBUG -DENABLE_DEBUG_LOG -DCMAKE_EXE_LINKER_FLAGS=-pthread -DEXTERNAL_INCLUDE_DIR=

-- Build Type: [debug]
CMake Error at cmake/libtuv.cmake:48 (target_include_directories):
  target_include_directories called with invalid arguments
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)

-- Configuring incomplete, errors occurred!

**Comment by LaszloLango** [comment]
Could you provide more info for us? What is your OS and GCC version?

**Comment by gridnow** [comment]
$gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$cmake --version
cmake version 2.8.11

$python --version
Python 2.7.5

os
centos7

**Comment by akiss77** [comment]
@gridnow I've managed to track down the issue.

In short: please, update your cmake to 2.8.12 at least.

A bit longer explanation: `libtuv/cmake/libtuv.cmake` has a line
`target_include_directories(${TARGETLIBNAME} SYSTEM PRIVATE ${TARGET_INC})`
According to cmake manuals, the `SYSTEM` argument was introduced in 2.8.12 only:
* 2.8.11: https://cmake.org/cmake/help/v2.8.11/cmake.html#command:target_include_directories
* 2.8.12: https://cmake.org/cmake/help/v2.8.12/cmake.html#command:target_include_directories

Unfortunately, the minimum version requirement for cmake was specified only as 2.8. If that were correct (2.8.12), then your build would have bailed out earlier with a more informative error message.

What's more, this is actually not an iot.js issue but a libtuv issue. Once fixed in that upstream repo, a submodule update in iot.js will get it right here as well.

But the bottom line is that the fix will only mean that the minimum cmake version will become 2.8.12. Thus, you will need an update for your cmake.

**Comment by gridnow** [comment]
build ok。thanks。
