### ISSUE TITLE
Enhance UV exception on |CreateUVException|.

### ISSUE THREAD

**Issue by hyunjunekim** [Samsung/iotjs#426]
We should print some more information such as 'node.js'.
I guess that we need to fix up |CreateUVException| function, and also |After| function.

**Comment by glistening** [comment]
Currently we use iotjs_create_uv_exception (renamed from CreateUVException), it uses uv error number, and shows error string defined in libtuv/include/uv__error.h. We removedd some of the error strings from uv since we want to reduce footprint. What error messages do you need? Could you please explain more what fix up do you want? Furthermore, there are errors from jerryscript. It does not print error string by default probably for the same reason (footprint). You can enable further message if you build jerry by enabling more error string.

**Comment by hyunjunekim** [comment]
@glistening Could you check this codes on 'module_fs'?
https://github.com/Samsung/iotjs/blob/master/src/module/iotjs_module_fs.c#L72
> Always print 'open' function then occur to error.

And i think this issue is ambiguous about context. So also closed this issue. Thank you.
