### ISSUE TITLE
Assertion Failure ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p) after running Promise

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#845]
I got the following assertion failure on Linux x86_64:

### Error message
```
ICE: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed at /home/brian/iotjs/iotjs/deps/jerry/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_string_list):42.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

### promise.js (Test case)
```
var p = new Promise(function(resolve, reject) {
  resolve("resolved!");
});

p.then(function (msg) {
  console.log("promise " + msg);
});
```

### How to Build and Run
```
$ ./tools/build.py --jerry-profile=es2015-subset
$ ./build/x86_64-linux/debug/bin/iotjs promise.js
```

### jerryscript standalone and node.js works well.

```
$ node ../iotjs/promise.js
promise resolved!
$ ./build/bin/jerry ../iotjs/promise.js 
promise resolved!
```

**Comment by akosthekiss** [comment]
I've seen similar things when experimenting with promises in jerry. To me, this happened when there were still enqueued promise jobs when calling jerry_cleanup. (I guess, without looking at any code I admit, that nothing executes the enqueued promise jobs in iotjs, yet. I.e., jerry is built with promise support, the js code uses them, jerry enqueues jobs as asked, but at the end, nothing runs them. And the enqueued jobs will keep references to many things (it's not just the string reference, there are many others, this is just the first triggered failure), which will lead to an assert at cleanup, because jerry expects that everything is released.)

**Comment by LaszloLango** [comment]
IMHO, we should wait for https://github.com/jerryscript-project/jerryscript/pull/1804 to land first and update JerryScript submodule in IoT.js.

**Comment by glistening** [comment]
@akosthekiss @LaszloLango Your comments helped me much. Thank you.

**Comment by glistening** [comment]
@akosthekiss, @LaszloLango I fixed the assertion failure by putting `jerry_port_default_jobqueue_run` as the guide added in jerryscript-project/jerryscript#1804. I will push iotjs Promise support PR after jerryscript-project/jerryscript#1804 is landed.

**Comment by yichoi** [comment]
jerryscript-project/jerryscript#1804 has landed. @LaszloLango would you please update Jerryscript submodule in IoT.js?

**Comment by LaszloLango** [comment]
@yichoi sure, I'll do it.

**Comment by LaszloLango** [comment]
#859 is landed.
